# Generated by Django 6.0.4 on 2026-04-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('vibration', models.FloatField()),
                ('rpm', models.IntegerField()),
                ('pressure', models.FloatField()),
                ('prediction', models.IntegerField()),
                ('label', models.CharField(choices=[('Normal', 'Normal'), ('Anomaly', 'Anomaly')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
