# Generated by Django 6.0.4 on 2026-04-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='anomaly_score',
            field=models.FloatField(default=0.0),
        ),
    ]
