# Generated by Django 6.0.4 on 2026-05-01 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_predictionhistory_anomaly_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionhistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
